version: "3"

services:
  db:
    image: mongo
    restart: unless-stopped
    hostname: db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    expose:
      - 27017
    volumes:
      - db_volume:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: mongod --quiet --logpath /dev/null

  server:
    restart: on-failure
    build:
      context: .
      target: server_production
    hostname: server
    env_file:
      - .env
      - .env.production
    expose:
      - ${PORT}
    depends_on:
      - db
    links:
      - db

  nginx:
    build:
      context: .
      target: nginx_no-client
    links:
      - server
    depends_on:
      - db
      - server
    ports:
      - "80:80"
      - "443:443"

volumes:
  db_volume:
