version: "3"

services:
  strapi:
    env_file:
      - strapi/.env
    build:
      target: strapi_development
    ports:
      - 1337:1337
    volumes:
      - ./strapi:/app
      - /app/node_modules

  client:
    build:
      target: client_development
    ports:
      - "3000:3000"
    depends_on:
      - strapi
    volumes:
      - ./client:/app
      - /app/node_modules
